### ISSUE TITLE
Polish recipe for migration JakartaEE Authz/Authn

### ISSUE THREAD

**Issue by mabartos** [openrewrite/rewrite-migrate-java#166]
After resolving issue #160, some changes were added[1], and I think it's necessary to polish a particular aspect of these changes. For recipe `JavaxAuthorizationMigrationToJakartaAuthorization`, the Maven Add dependency step was added and IMHO, there's a certain inaccuracy in it. 

Current one:
```
- org.openrewrite.maven.AddDependency:
      groupId: jakarta.authorization
      artifactId: jakarta.authorization-api
      version: 2.x
      onlyIfUsing: jakarta.security.jacc..*
```

Proposed one:
```
- org.openrewrite.maven.AddDependency:
      groupId: jakarta.authorization
      artifactId: jakarta.authorization-api
      version: 2.x
      onlyIfUsing: javax.security.jacc..*
```

The prop `onlyIfUsing` was changed from `jakarta.security.jacc..*` to `javax.security.jacc..*`. IMHO, it makes more sense in this context as we add the new dependency when there's some reference to the old package in a codebase. 
When in the codebase, the new reference to package `jakarta.security.jacc..*` is used, we assume the new dependency is already included in the project due to the fact it would not be possible to compile the project.

WDYT? cc: @tkvangorder

[1] https://github.com/openrewrite/rewrite-migrate-java/commit/c06ccc96ceb11077858b4a3487fe4c74037771f6
