### ISSUE TITLE
Java.version downgraded from 17 to 11

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-migrate-java#169]
When running [UpgradeToJava17](https://docs.openrewrite.org/reference/recipes/java/migrate/upgradetojava17) on a Java 17 Spring Boot project already using a `java.version` property with value `17`, that value gets downgraded tot 11.

To replicate:

1. Checkout https://github.com/timtebeek/kafka-dead-letter-publishing.git
2. Run the migration

> mvn org.openrewrite.maven:rewrite-maven-plugin:4.38.2:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:1.15.0 \
  -DactiveRecipes=org.openrewrite.java.migrate.UpgradeToJava17

**Expected**
Java.version property in pom.xml remains at 17.

**Actual**
Java.version property in pom.xml is changed to 11.

**Comment by sambsnyd** [comment]
Looks like the recipe will always overwrite whatever is there with "11". Needs to be conditionalized, perhaps with an applicability test.
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.migrate.JavaVersion11
displayName: Change Maven Java version property values to 11
description: Change maven.compiler.source and maven.compiler.target values to 11.
recipeList:
  - org.openrewrite.maven.ChangePropertyValue:
      key: java.version
      newValue: 11
      addIfMissing: false
```
