### ISSUE TITLE
Recipe to update jaxb-maven-plugin to 2.5.0 (or higher)

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-migrate-java#26]
There is a Maven plugin for generating code from XSDs and this must be updated to a version that supports Java 11:

Version `2.5.0` of the plugin supports Java 11.

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>jaxb2-maven-plugin</artifactId>
        <version>2.5.0</version>
      </plugin>
```
See this issue for more details: https://github.com/mojohaus/jaxb2-maven-plugin/issues/43

**Comment by aegershman** [comment]
For the time being, even though UpgradePluginVersion doesn't support consuming versions from a parent pom, etc., would something like this declarative recipe be sufficient?

```yml
  - org.openrewrite.maven.UpgradePluginVersion:      
        groupId: org.codehaus.mojo
        artifactId: jaxb2-maven-plugin
        newVersion: 2.5.x
```
