### ISSUE TITLE
Jakarta EE10: Faces 2.x to 4.x Migration

### ISSUE THREAD

**Issue by melloware** [openrewrite/rewrite-migrate-java#368]
## What problem are you trying to solve?
Converting a JSF 2.X to Faces 4.0 (EE10) application I would like to rewrite all Faces Namespaces in XHTML files to their new EE10 equivalent.

## What precondition(s) should be checked before applying this recipe?
EE10 only and to XHTML files only.

## Describe the situation before applying the recipe

**Before (JSF 2.2 java.sun.com):**
```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
   xmlns:ui="http://java.sun.com/jsf/facelets"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:f="http://java.sun.com/jsf/core"
   xmlns:c="http://java.sun.com/jsp/jstl/core">
```

**Before (JSF 2.3 xmlns.jcp.org):**
```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
   xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
   xmlns:h="http://xmlns.jcp.org/jsf/html"
   xmlns:f="http://xmlns.jcp.org/jsf/core"
   xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
```

**After (JSF 4.0 EE10):**
```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="jakarta.faces.facelets"
                xmlns:h="jakarta.faces.html"
                xmlns:f="jakarta.faces.core"
                xmlns:c="jakarta.tags.core"
>
```

**Comment by timtebeek** [comment]
Interesting suggestion @melloware ! Right now we parse (x)html as text, but I guess there's little stopping us from attempting to parse it as XML to allow recipes to make structured changes. That would then unlock recipes to make the above changes through OpenRewrite to complete a migration. Thanks for the proposal!

**Comment by melloware** [comment]
This would make migrating JSF apps that have hundreds of pages so much better!  We could technically parse it as text and just do the replacement?  I have a few other JSF EE10 related suggestions should I open new tickets?

**Comment by timtebeek** [comment]
What's the extension you use for your JSF templates? I recently did a push to standardize which files we parse as PlainText
- https://github.com/openrewrite/rewrite-maven-plugin/commit/d35c59c83c1369640b2df6a930373a870fa7e202
- https://github.com/openrewrite/rewrite-gradle-plugin/commit/52e0f1ec7f66acba95274ce9e1f9a50fc6d758ff 

We could follow that up with additional patterns if that would help your use case here.

And welcome to open additional issues; do I understand correctly that you'd also be willing to take some of those on for the implementation?

**Comment by melloware** [comment]
If you give me guidance I am more than happy to help i literally just discovered this project today as I was about to write a JSF EE8 to EE10 converter because I have 70+ projects for a client to convert!

I will open a few more tickets

**Comment by timtebeek** [comment]
Sure! If we go for parsing these files as plaintext (depending on their file extension) we could use this recipe for the replacements:
https://docs.openrewrite.org/recipes/text/findandreplace

If we instead go for parsing these files as xml, then we could use this recipe instead: https://docs.openrewrite.org/recipes/xml/changetagattribute

You can compose these recipes in our recipe builder, and run them against OSS projects if you want to try these out.
https://app.moderne.io/recipes/builder

Hope that helps!

**Comment by melloware** [comment]
OK I think I will try the plain text route as it is actually a pretty simple replacement which I did in Notepad++ over hundreds of files without fail.

**Comment by timtebeek** [comment]
For the XML files I'd opt for the XML recipes, those we can incorporate here as well, as commented on those individual issues.

And welcome to the project! Great to see you immediately want to get started :)

**Comment by melloware** [comment]
This works like a charm just ran it against a large project.  If you give me a hint on where I should put this in the code base I can submit a a PR?

```yml
type: specs.openrewrite.org/v1beta/recipe
name: com.melloware.JakartaFacesXhtmlNamespaces
displayName: Find and replace legacy JSF namespaces with Jakarta namespaces in XHTML files
recipeList:
  - org.openrewrite.text.FindAndReplace:
      find: "http://java.sun.com/jsf/html"
      replace: "jakarta.faces.html"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://xmlns.jcp.org/jsf/html"
      replace: "jakarta.faces.html"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://java.sun.com/jsf/facelets"
      replace: "jakarta.faces.facelets"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://xmlns.jcp.org/jsf/facelets"
      replace: "jakarta.faces.facelets"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://java.sun.com/jsf/core"
      replace: "jakarta.faces.core"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://xmlns.jcp.org/jsf/core"
      replace: "jakarta.faces.core"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://java.sun.com/jsp/jstl/core"
      replace: "jakarta.tags.core"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
  - org.openrewrite.text.FindAndReplace:
      find: "http://xmlns.jcp.org/jsp/jstl/core"
      replace: "jakarta.tags.core"
      regex: null
      caseSensitive: null
      multiline: null
      dotAll: null
      filePattern: '**/*.xhtml'
```

**Comment by timtebeek** [comment]
Glad to hear that works for you! Did you do anything special to have those `xhtml` files treated as plain text?

I think that recipe above could best go into a new file called `jakarta-faces-4.yml` in this directory:
https://github.com/openrewrite/rewrite-migrate-java/tree/main/src/main/resources/META-INF/rewrite
You can leave out the `null` fields and be sure to give it a description too. Thanks for adding this so quickly!

**Comment by melloware** [comment]
Thanks PR submitted I went through the MyFaces codebase (I am a committer there) and found all the namespaces.

**Comment by melloware** [comment]
@timtebeek Just need your help on one thing.  I have this recipe.

```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.migrate.jakarta.FacesEcmaScript
displayName: Migrate JSF values inside EcmaScript files
description: Convert JSF to Faces values inside JavaScript/TypeScript files
tags:
  - jakarta
  - faces
  - jsf
recipeList:
  - org.openrewrite.text.FindAndReplace:
      find: javax
      replace: jakarta
      filePattern: '**/*.js;**/*.ts;**/*.properties'
  - org.openrewrite.text.FindAndReplace:
      find: window.jsf
      replace: window.faces
      filePattern: '**/*.js;**/*.ts'
  - org.openrewrite.text.FindAndReplace:
      find: jsf.ajax
      replace: faces.ajax
      filePattern: '**/*.js;**/*.ts'
```

I am trying to find all JS and TS files and replace these specific values inside those files.  I have tried everything and its not working I have example projects with JS files 

For example a file location in my code here: `\src\main\resources\META-INF\resources\primefaces\core\core.csp.js`

Is not being found and replaced.  I have tried changing the `glob` pattern but eveyrthing I am reading says `**/*.js` should recurse and find all JS files no matter where it is?
