### ISSUE TITLE
Recipe should migrate from javax to jakarta but is doing opposite

### ISSUE THREAD

**Issue by achimmihca** [openrewrite/rewrite-migrate-java#679]
## What version of OpenRewrite are you using?

I am using

- org.openrewrite.maven: 6.2.0
- org.openrewrite.recipe.rewrite-spring: 6.2.0

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.

## What is the smallest, simplest way to reproduce the problem?

Use jakarta.annotation.Nullable or jakarta.annotation.Nonnull

```java
import jakarta.annotation.Nullable;

public interface MyInterface {
    String getFullName(@Nullable firstName);
}
```

## What did you expect to see?
The code should not change because it already uses jakarta annotations (instead of javax annotations).

## What did you see instead?
Import is rewritten to use javax:

```java
import javax.annotation.Nullable;

public interface MyInterface {
    String getFullName(@Nullable firstName);
}
```

## What is the full stack trace of any errors you encountered?
```
[WARNING] These recipes would make changes to src\main\java\com\myproject\MyInterface.java:
[WARNING]     org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_3
[WARNING]         org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
[WARNING]             org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1
[WARNING]                 org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0
[WARNING]                     org.openrewrite.java.migrate.jakarta.JavaxMigrationToJakarta
[WARNING]                         org.openrewrite.java.migrate.jakarta.JavaxAnnotationMigrationToJakartaAnnotation
[WARNING]                             org.openrewrite.java.ChangeType: {oldFullyQualifiedTypeName=jakarta.annotation.Nullable, newFullyQualifiedTypeName=javax.annotation.Nullable}
```

## Are you interested in Contributing a fix to OpenRewrite

I think there are some swapped properties (`old...` vs. `new...`) in the yaml file for [JavaxMigrationToJakarta](src/main/resources/META-INF/rewrite/jakarta-ee-9.yml)

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.migrate.jakarta.JavaxAnnotationMigrationToJakartaAnnotation
displayName: Migrate deprecated `javax.annotation` to `jakarta.annotation`
description: Java EE has been rebranded to Jakarta EE, necessitating a package relocation.
tags:
  - annotation
  - javax
  - jakarta
recipeList:
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: javax.annotation
      oldArtifactId: javax.annotation-api
      newGroupId: jakarta.annotation
      newArtifactId: jakarta.annotation-api
      newVersion: 2.0.x
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: org.glassfish.main
      oldArtifactId: javax.annotation
      newGroupId: jakarta.annotation
      newArtifactId: jakarta.annotation-api
      newVersion: 2.0.x
  - org.openrewrite.java.ChangePackage:
      oldPackageName: javax.annotation
      newPackageName: jakarta.annotation
      recursive: true
  - org.openrewrite.java.ChangePackage:
      oldPackageName: jakarta.annotation.processing             <<< old should be javax ?
      newPackageName: javax.annotation.processing               <<< new should be jakarta ?
  - org.openrewrite.java.ChangePackage:
      oldPackageName: jakarta.annotation.concurrent             <<< old should be javax ?
      newPackageName: javax.annotation.concurrent               <<< new should be jakarta ?
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: jakarta.annotation.Nullable    <<< old should be javax ?
      newFullyQualifiedTypeName: javax.annotation.Nullable      <<< new should be jakarta ?
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: jakarta.annotation.Nonnull     <<< old should be javax ?
      newFullyQualifiedTypeName: javax.annotation.Nonnull       <<< new should be jakarta ?
```
